/**
 * Stable, spec-mandated error codes (R2M_V5_ARCHITECTURE_AND_IMPLEMENTATION_PLAN.md §10).
 * Never return ad-hoc business error strings — extend this catalogue instead.
 */
export const ErrorCode = {
  // AUTH_*
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
  AUTH_INVALID_REFRESH_TOKEN: "AUTH_INVALID_REFRESH_TOKEN",
  AUTH_UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_EMAIL_ALREADY_REGISTERED: "AUTH_EMAIL_ALREADY_REGISTERED",

  // ORG_*
  ORG_ALREADY_EXISTS: "ORG_ALREADY_EXISTS",
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  ORG_NOT_ACTIVE: "ORG_NOT_ACTIVE",
  ORG_INVALID_TRANSITION: "ORG_INVALID_TRANSITION",
  ORG_VERSION_CONFLICT: "ORG_VERSION_CONFLICT",
  ORG_CANNOT_REMOVE_LAST_OWNER: "ORG_CANNOT_REMOVE_LAST_OWNER",
  ORG_MEMBER_ALREADY_EXISTS: "ORG_MEMBER_ALREADY_EXISTS",
  ORG_MEMBER_NOT_FOUND: "ORG_MEMBER_NOT_FOUND",
  ORG_NOT_MEMBER: "ORG_NOT_MEMBER",

  // VERIFICATION_*
  VERIFICATION_ALREADY_PENDING: "VERIFICATION_ALREADY_PENDING",
  VERIFICATION_REQUEST_NOT_FOUND: "VERIFICATION_REQUEST_NOT_FOUND",
  VERIFICATION_REQUEST_CONFLICT: "VERIFICATION_REQUEST_CONFLICT",
  VERIFICATION_REVIEWER_IS_SUBMITTER: "VERIFICATION_REVIEWER_IS_SUBMITTER",
  VERIFICATION_REASON_REQUIRED: "VERIFICATION_REASON_REQUIRED",
  VERIFICATION_INVALID_TRANSITION: "VERIFICATION_INVALID_TRANSITION",

  // SYSTEM_* (Platform Operations: audit/outbox/idempotency — cross-cutting, no single UC-* group in §10)
  SYSTEM_IDEMPOTENCY_KEY_REUSED: "SYSTEM_IDEMPOTENCY_KEY_REUSED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
