/**
 * Stable, spec-mandated error codes (R2M_V5_ARCHITECTURE_AND_IMPLEMENTATION_PLAN.md §10).
 * Never return ad-hoc business error strings — extend this catalogue instead.
 */
export const ErrorCode = {
  // AUTH_*
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
  AUTH_INVALID_REFRESH_TOKEN: "AUTH_INVALID_REFRESH_TOKEN",
  AUTH_UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_EMAIL_ALREADY_REGISTERED: "AUTH_EMAIL_ALREADY_REGISTERED",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_EMAIL_VERIFICATION_TOKEN_INVALID: "AUTH_EMAIL_VERIFICATION_TOKEN_INVALID",
  AUTH_EMAIL_VERIFICATION_TOKEN_EXPIRED: "AUTH_EMAIL_VERIFICATION_TOKEN_EXPIRED",
  AUTH_EMAIL_VERIFICATION_RATE_LIMITED: "AUTH_EMAIL_VERIFICATION_RATE_LIMITED",

  // ORG_*
  ORG_ALREADY_EXISTS: "ORG_ALREADY_EXISTS",
  ORG_DOMAIN_ALREADY_REGISTERED: "ORG_DOMAIN_ALREADY_REGISTERED",
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  ORG_NOT_ACTIVE: "ORG_NOT_ACTIVE",
  ORG_INVALID_TRANSITION: "ORG_INVALID_TRANSITION",
  ORG_VERSION_CONFLICT: "ORG_VERSION_CONFLICT",
  ORG_CANNOT_REMOVE_LAST_OWNER: "ORG_CANNOT_REMOVE_LAST_OWNER",
  ORG_MEMBER_ALREADY_EXISTS: "ORG_MEMBER_ALREADY_EXISTS",
  ORG_MEMBER_NOT_FOUND: "ORG_MEMBER_NOT_FOUND",
  ORG_NOT_MEMBER: "ORG_NOT_MEMBER",

  // VERIFICATION_*
  VERIFICATION_ALREADY_PENDING: "VERIFICATION_ALREADY_PENDING",
  VERIFICATION_REQUEST_NOT_FOUND: "VERIFICATION_REQUEST_NOT_FOUND",
  VERIFICATION_REQUEST_CONFLICT: "VERIFICATION_REQUEST_CONFLICT",
  VERIFICATION_REVIEWER_IS_SUBMITTER: "VERIFICATION_REVIEWER_IS_SUBMITTER",
  VERIFICATION_REASON_REQUIRED: "VERIFICATION_REASON_REQUIRED",
  VERIFICATION_INVALID_TRANSITION: "VERIFICATION_INVALID_TRANSITION",
  VERIFICATION_MISSING_DOCUMENT: "VERIFICATION_MISSING_DOCUMENT",

  // SYSTEM_* (Platform Operations: audit/outbox/idempotency — cross-cutting, no single UC-* group in §10)
  SYSTEM_IDEMPOTENCY_KEY_REUSED: "SYSTEM_IDEMPOTENCY_KEY_REUSED",

  // AUTHOR_* (UC-VER-01/02 applied to author verification — reuses VERIFICATION_* codes
  // above for the request lifecycle itself; these cover author-specific checks only)
  AUTHOR_ALREADY_VERIFIED: "AUTHOR_ALREADY_VERIFIED",
  AUTHOR_VERIFICATION_DOCUMENT_INVALID: "AUTHOR_VERIFICATION_DOCUMENT_INVALID",
  AUTHOR_INVALID_TRANSITION: "AUTHOR_INVALID_TRANSITION",

  // RESOURCE_* (UC-RES-01/02)
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_VERSION_NOT_FOUND: "RESOURCE_VERSION_NOT_FOUND",
  RESOURCE_VERSION_IMMUTABLE: "RESOURCE_VERSION_IMMUTABLE",
  RESOURCE_INVALID_TYPE_FOR_PAPER_METADATA: "RESOURCE_INVALID_TYPE_FOR_PAPER_METADATA",
  RESOURCE_CONTENT_NOT_FOUND: "RESOURCE_CONTENT_NOT_FOUND",
  RESOURCE_INVALID_TRANSITION: "RESOURCE_INVALID_TRANSITION",
  RESOURCE_ACCESS_DENIED: "RESOURCE_ACCESS_DENIED",
  RESOURCE_AUTHOR_NOT_VERIFIED: "RESOURCE_AUTHOR_NOT_VERIFIED",

  // ANNOTATION_* (UC-RES-02)
  ANNOTATION_NOT_FOUND: "ANNOTATION_NOT_FOUND",
  ANNOTATION_EMPTY_CONTENT: "ANNOTATION_EMPTY_CONTENT",
  ANNOTATION_TARGET_LOCATOR_INVALID: "ANNOTATION_TARGET_LOCATOR_INVALID",

  // ACCESS_GRANT_* (SUC-04 — tự đề xuất, xem plan PHẦN B.0.1)
  ACCESS_GRANT_NOT_FOUND: "ACCESS_GRANT_NOT_FOUND",
  ACCESS_GRANT_DUPLICATE: "ACCESS_GRANT_DUPLICATE",
  ACCESS_GRANT_ALREADY_REVOKED: "ACCESS_GRANT_ALREADY_REVOKED",

  // CASE_* (UC-CASE-01, §3.5/§3.6 01_workflow_theo_phase.md)
  CASE_NOT_FOUND: "CASE_NOT_FOUND",
  CASE_CREATOR_NOT_VERIFIED_AUTHOR: "CASE_CREATOR_NOT_VERIFIED_AUTHOR",
  CASE_OWNER_ALREADY_EXISTS: "CASE_OWNER_ALREADY_EXISTS",
  CASE_MEMBER_ALREADY_EXISTS: "CASE_MEMBER_ALREADY_EXISTS",
  CASE_OWNER_NOT_IN_OWNING_ORG: "CASE_OWNER_NOT_IN_OWNING_ORG",
  CASE_MEMBER_NOT_ACTIVE_IN_ORGANIZATION: "CASE_MEMBER_NOT_ACTIVE_IN_ORGANIZATION",
  CASE_PARTNER_MEMBER_ORG_NOT_LINKED: "CASE_PARTNER_MEMBER_ORG_NOT_LINKED",
  CASE_ORGANIZATION_ROLE_NOT_ALLOWED: "CASE_ORGANIZATION_ROLE_NOT_ALLOWED",
  CASE_INVALID_TRANSITION: "CASE_INVALID_TRANSITION",

  // EVIDENCE_* (UC-EVD-01)
  EVIDENCE_NOT_FOUND: "EVIDENCE_NOT_FOUND",
  CASE_EVIDENCE_REQUIRES_CITATION: "CASE_EVIDENCE_REQUIRES_CITATION",
  CASE_EVIDENCE_ROLE_NOT_ALLOWED: "CASE_EVIDENCE_ROLE_NOT_ALLOWED",

  // ASSESSMENT_* (UC-ASM-01) — tên khớp chuỗi RAISE EXCEPTION trong
  // production_constraints_and_indexes.sql (ưu tiên hơn danh sách tóm tắt §4.6, xem plan
  // PHẦN D quyết định 10).
  ASSESSMENT_NOT_FOUND: "ASSESSMENT_NOT_FOUND",
  ASSESSMENT_HAS_NO_SCORES: "ASSESSMENT_HAS_NO_SCORES",
  ASSESSMENT_SCORE_OUT_OF_RANGE: "ASSESSMENT_SCORE_OUT_OF_RANGE",
  ASSESSMENT_CRITERION_NOT_FOUND: "ASSESSMENT_CRITERION_NOT_FOUND",
  ASSESSMENT_CRITERION_FRAMEWORK_MISMATCH: "ASSESSMENT_CRITERION_FRAMEWORK_MISMATCH",
  ASSESSMENT_SCORE_MISSING_EVIDENCE: "ASSESSMENT_SCORE_MISSING_EVIDENCE",
  ASSESSMENT_SCORE_MISSING_CITATION: "ASSESSMENT_SCORE_MISSING_CITATION",
  ASSESSMENT_INVALID_TRANSITION: "ASSESSMENT_INVALID_TRANSITION",
  ASSESSMENT_FRAMEWORK_NOT_FOUND: "ASSESSMENT_FRAMEWORK_NOT_FOUND",

  // GAP_* (UC-GAP-01)
  GAP_NOT_FOUND: "GAP_NOT_FOUND",
  GAP_SEVERITY_REQUIRED: "GAP_SEVERITY_REQUIRED",
  GAP_MISSING_SUPPORT: "GAP_MISSING_SUPPORT",
  GAP_RESOLUTION_NOTE_REQUIRED: "GAP_RESOLUTION_NOTE_REQUIRED",
  GAP_INVALID_TRANSITION: "GAP_INVALID_TRANSITION",

  // ROADMAP_* (UC-RDM-01) — tên khớp chuỗi RAISE EXCEPTION trong SQL mẫu (quyết định 10).
  ROADMAP_NOT_FOUND: "ROADMAP_NOT_FOUND",
  MILESTONE_NOT_FOUND: "MILESTONE_NOT_FOUND",
  MILESTONE_DEPENDENCY_CYCLE_DETECTED: "MILESTONE_DEPENDENCY_CYCLE_DETECTED",
  MILESTONE_DEPENDENCIES_MUST_BE_IN_SAME_ROADMAP: "MILESTONE_DEPENDENCIES_MUST_BE_IN_SAME_ROADMAP",
  ROADMAP_HAS_NO_MILESTONES: "ROADMAP_HAS_NO_MILESTONES",
  ROADMAP_HAS_UNRESOLVED_CRITICAL_GAPS: "ROADMAP_HAS_UNRESOLVED_CRITICAL_GAPS",
  ROADMAP_INVALID_TRANSITION: "ROADMAP_INVALID_TRANSITION",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
